name: Send scheduled mail

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:


permissions:
  contents: read


jobs:
  send-mail:

    runs-on: ubuntu-latest

    steps:

      - name: Send email

        uses: dawidd6/action-send-mail@v3

        with:

          server_address: ${{ secrets.MAIL_SERVER }}

          server_port: ${{ secrets.MAIL_PORT }}

          secure: ${{ secrets.MAIL_SECURE }}

          username: ${{ secrets.MAIL_USERNAME }}

          password: ${{ secrets.MAIL_PASSWORD }}

          from: ${{ secrets.MAIL_FROM }}

          to: ${{ secrets.MAIL_TO }}

          subject: ${{ secrets.MAIL_SUBJECT }}

          body: |
            GitHub Actions 自动邮件

            Repository:
            ${{ github.repository }}

            Workflow:
            ${{ github.workflow }}

            Run ID:
            ${{ github.run_id }}
